### PR TITLE
fiber sparameters

### PR DESCRIPTION
**Pull request by joamatab**
this PR calculates the Sparameters for an arbitrary grating coupler

it still needs some work to match the same grating simulation in lumerical 2D FDTD results with an efficiency of 3dB

image

### CODE REVIEW

**Comment by simbilod** [comment]
Thanks for the organizational updates -- this is a good way forward.

While I haven't been able to get the plot you show (is that using the default parameters you added in fiber.py?), and therefore cannot confirm this, the results seem to be close to what you expect near the center of the wavelength band, and drop away. This is known to occur when frequencies are requested in the mode monitors that are poorly-represented in the source pulse. Try playing with the bandwidth of the GaussianSource. Right now it's 0.1*fcen. With fcen = c/1.55E-6 = 193THz, this means the pulse FWHM extends from ~184 THz to 202 THz. You are requesting frequencies to be sampled from c/1.6E-6 = 187 THz to c/1.5E-6 = 200 THz, which may be cutting it close. You could also repeat the FDTD simulation with different center frequencies to see how well the off-center frequencies are doing in the "broadband" simulation.

There is also the question as to whether there is something setup differently between the MEEP and Lumerical sims. In the past I've been able to get sensibly the same results from MEEP and Lumerical at the center frequency I was studying.

Aside: Also while mpirun is not enabled from Python per say as of now, from the terminal doing `mpirun -np 10 python fiber.py` instead of just `python fiber.py` does work. Might save you some time!

**Comment by joamatab** [comment]
Hi Simon, 

the plot was done using lumerical

The transmission for this script does match

**Comment by simbilod** [comment]
Oh that makes sense. Glad it works now!

**Comment by joamatab** [comment]
sorry, i meant that the transmission for this script does not match

**Comment by smartalecH** [comment]
FYI Meep's `GaussianBeamSource` source object implements the Green's function of a 3D Gaussian beam for both 2D *and* 3D, which isn't correct (the two are very different). In 2D, it's a good enough approximation, but still introduces error.

Eventually we want to implement the proper Green's function, but that will take time (and effort).

In other words, Lumerical and Meep should differ significantly if you are using a `GaussianBeamSource` in 2D.

**Comment by smartalecH** [comment]
*Also* Meep's Greene's function is computed at a single frequency. Ideally, you would compute the Green's function at multiple frequencies (if you were looking at a broadband result) and fit the frequency profile to a time-domain source *at each spatial point*. I'm pretty sure Lumerical does this fitting (I know they do it for their mode sources).

**Comment by simbilod** [comment]
Thanks for chiming in Alec. This could explain why I thought I had a match, since in my case I was looking at a single frequency with only the waveguide as the source and fiber a monitor port.

**Comment by joamatab** [comment]
with the current sim setup there is a 17dB difference in the meet Sparameter results compared to Lumerical

image

**Pull request merged**
